#!/usr/bin/env python3
"""
Upload YouTube Summary to GitHub Gist
======================================
Usage: python3 upload-gist.py <summary_md> <transcript_txt> <title>

Reads GITHUB_TOKEN from ~/.hermes/.env
"""

import sys
import os
import json
import urllib.request
import datetime


def read_token():
    """Read GitHub token from ~/.hermes/.env"""
    env_path = os.path.expanduser("~/.hermes/.env")
    try:
        with open(env_path) as f:
            for line in f:
                if line.startswith("GITHUB_TOKEN="):
                    token = line.split("=", 1)[1].strip()
                    if token:
                        return token
    except FileNotFoundError:
        pass
    return None


def upload(summary_md, transcript_txt, title):
    """Upload to GitHub Gist via raw API."""
    token = read_token()
    if not token:
        print("❌ GITHUB_TOKEN not found in ~/.hermes/.env")
        sys.exit(1)

    # Format the summary
    timestamp = datetime.datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    formatted = f"""# 🎬 {title}

**來源**: YouTube
**上傳時間**: {timestamp}

---

{summary_md}

---
*Generated by youtube-summary skill*
"""

    # Build payload with safe JSON encoding
    payload = {
        "description": f"YouTube Summary: {title[:80]}",
        "public": True,
        "files": {
            "summary.md": {"content": formatted},
            "transcript.txt": {"content": transcript_txt[:100000]}
        }
    }

    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")

    req = urllib.request.Request(
        "https://api.github.com/gists",
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
            "User-Agent": "pi-youtube-summary"
        }
    )

    try:
        resp = urllib.request.urlopen(req, timeout=30)
        gist_data = json.loads(resp.read().decode())
        print(f"✅ Gist URL: {gist_data['html_url']}")
        return gist_data["html_url"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()
        print(f"❌ Gist upload failed: HTTP {e.code}")
        print(error_body[:500])
        sys.exit(1)


def main():
    if len(sys.argv) < 4:
        print("Usage: python3 upload-gist.py <summary_md> <transcript_txt> <title>")
        print()
        print("Example:")
        print('  python3 upload-gist.py "Summary content..." "Transcript..." "Video Title"')
        sys.exit(1)

    summary = sys.argv[1]
    transcript = sys.argv[2]
    title = sys.argv[3]

    upload(summary, transcript, title)


if __name__ == "__main__":
    main()
