#!/usr/bin/env python3
"""
Upload YouTube Summary to GitHub Gist
======================================
Usage:
    python3 upload-gist.py <summary_md> <transcript_txt> <title>
    python3 upload-gist.py <summary_file> <transcript_file> <title>   (auto-detect)

Auto-detects whether the first two args are file paths (existing files) or
raw content (any other text).  When file paths are detected, the content is
read into memory so the upload-gist payload is built from the actual file
contents — never from raw paths sent to the API.

Reads GITHUB_TOKEN from ~/.hermes/.env
"""

import sys
import os
import json
import urllib.request
import datetime
import tempfile


def read_token():
    """Read GitHub token from ~/.hermes/.env"""
    env_path = os.path.expanduser("~/.hermes/.env")
    try:
        with open(env_path) as f:
            for line in f:
                if line.startswith("GITHUB_TOKEN="):
                    token = line.split("=", 1)[1].strip()
                    if token:
                        return token
    except FileNotFoundError:
        pass
    return None


def load_content(arg):
    """Load content from a file if arg is an existing path, otherwise return arg as raw text."""
    if os.path.isfile(arg):
        with open(arg, "r", encoding="utf-8") as f:
            return f.read()
    return arg


def upload(summary_md, transcript_txt, title):
    """Upload to GitHub Gist via raw API."""
    token = read_token()
    if not token:
        print("❌ GITHUB_TOKEN not found in ~/.hermes/.env")
        sys.exit(1)

    # Format the summary
    timestamp = datetime.datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    formatted = f"""# 🎬 {title}

**來源**: YouTube
**原始連結**: {getattr(upload, '_video_url', 'https://youtube.com/watch?v=unknown')}
**上傳時間**: {timestamp}

---

{summary_md}

---
*Generated by youtube-summary skill*
"""

    # Build payload with safe JSON encoding
    payload = {
        "description": f"YouTube Summary: {title[:80]}",
        "public": True,
        "files": {
            "summary.md": {"content": formatted},
            "transcript.txt": {"content": transcript_txt[:100000]}
        }
    }

    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")

    req = urllib.request.Request(
        "https://api.github.com/gists",
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
            "User-Agent": "pi-youtube-summary"
        }
    )

    try:
        resp = urllib.request.urlopen(req, timeout=30)
        gist_data = json.loads(resp.read().decode())
        print(f"✅ Gist URL: {gist_data['html_url']}")
        return gist_data["html_url"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()
        print(f"❌ Gist upload failed: HTTP {e.code}")
        print(error_body[:500])
        sys.exit(1)


def main():
    if len(sys.argv) < 4:
        print("Usage: python3 upload-gist.py <summary_md> <transcript_txt> <title>")
        print("       python3 upload-gist.py <summary_file> <transcript_file> <title>")
        print()
        print("Auto-detects file paths vs raw content.")
        sys.exit(1)

    # Auto-detect: if the arg is an existing file, read its content; otherwise use as raw text
    summary = load_content(sys.argv[1])
    transcript = load_content(sys.argv[2])
    title = sys.argv[3]

    upload(summary, transcript, title)


if __name__ == "__main__":
    main()
